[package]
name = "DiscordBot"
version = "0.1.0"
authors = ["blain"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serenity = "0.9"
tokio = { version = "0.2", features = ["full"] }